// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxbtyHHqDHfEpl8nVlQJha4UKo48sO09g',
    appId: '1:275377835520:web:1adab3e05d65e0949192e5',
    messagingSenderId: '275377835520',
    projectId: 'mid-to-do-app',
    authDomain: 'mid-to-do-app.firebaseapp.com',
    storageBucket: 'mid-to-do-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAir7kucB3pL5Kda7FZsBMPtEE5BhD4OQ',
    appId: '1:275377835520:android:c36a50249edfe2969192e5',
    messagingSenderId: '275377835520',
    projectId: 'mid-to-do-app',
    storageBucket: 'mid-to-do-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClVPLmUywFzE5uo40ynbQIhL-o5hyStA0',
    appId: '1:275377835520:ios:968fbf217991aeec9192e5',
    messagingSenderId: '275377835520',
    projectId: 'mid-to-do-app',
    storageBucket: 'mid-to-do-app.firebasestorage.app',
    iosBundleId: 'com.example.midToDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClVPLmUywFzE5uo40ynbQIhL-o5hyStA0',
    appId: '1:275377835520:ios:968fbf217991aeec9192e5',
    messagingSenderId: '275377835520',
    projectId: 'mid-to-do-app',
    storageBucket: 'mid-to-do-app.firebasestorage.app',
    iosBundleId: 'com.example.midToDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxbtyHHqDHfEpl8nVlQJha4UKo48sO09g',
    appId: '1:275377835520:web:9286d9e59da9a3d39192e5',
    messagingSenderId: '275377835520',
    projectId: 'mid-to-do-app',
    authDomain: 'mid-to-do-app.firebaseapp.com',
    storageBucket: 'mid-to-do-app.firebasestorage.app',
  );
}
